### ISSUE TITLE
Potential bug in `function call()` after coming back-online?

### ISSUE THREAD

**Issue by wildhart** [jamauro/method#12]
After looking through the code for `call()` to see how it works, I noticed that `applyOptions.noRetry` is set to `true` when offline, but it's never set back to `false`.

https://github.com/jamauro/method/blob/43297c4b81795f3fcbf3b195a4bf6fa16db1b29e/method.js#L389-L400

`applyOptions` is a `const` object which exists within the closure of `createMethod()`, so it will use the same object on each invocation of `call()`.

Potentially could this cause a bug when back online after being offline:
* Call method while offline → `noRetry = true`
* Go back online
* Call the same method again, but for some reason the method fails (patchy internet connection, so maybe the device is actually offline even though `Meteor.status().connected` doesn't know it yet?
* The method fails and is never retried?

**Comment by jamauro** [comment]
Thanks, good catch! This has been fixed in `v1.7.2`
