### ISSUE TITLE
Conflict: Constraint mongo@1.16.1 is not satisfied by mongo 2.0.0-rc300.2.

### ISSUE THREAD

**Issue by mcorbelli** [jamauro/method#7]
meteor add jam:method
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint mongo@1.16.1 is not satisfied by mongo 2.0.0-rc300.2.
Constraints on package "mongo":
* mongo@2.0.0-rc300.2 <- top level
* mongo@~2.0.0-rc300.2 <- top level
* mongo@2.0.0-rc300.2 <- accounts-base 3.0.0-rc300.2 <- accounts-password 3.0.0-rc300.2
* mongo@1.16.1 || 2.0.0-rc300.0 <- alanning:roles 4.0.0-alpha.3
* mongo@2.0.0-rc300.2 <- mongo-livedata 1.0.13-rc300.2 <- dburles:collection-helpers 1.0.0
* mongo@1.10.1 || 1.12.0 || 2.0.0-beta300.0 <- aldeed:collection2 4.0.1
* mongo@1.16.1 <- jam:method 1.5.1

**Comment by jamauro** [comment]
I've just published `v1.6.0-rc.4` that's compatible with the latest Meteor 3.0 release candidate that resolves this issue.
